# [build-system]
# requires = [""]

[tool.setuptools]
packages = ["ReachMM"]

[project]
name = "ReachMM"
version = "0.0.1"
dependencies = [
    "numpy",
    "sympy",
    "scipy",
    "tqdm",
    "shapely",
    "matplotlib",
    "casadi",
    "tabulate",
    "polytope"
]
